name: BanLaptop Testing

on:
  pull_request:
    branches:
    - staging
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: development
      SECRET_KEY: secret_key
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.4

      - run: python -m pip install --upgrade
      - run: pip install -r requirements.txt
      - run: python manage.py test